server:
  port: 6081
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v2/cars/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v2/brands/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v2/types/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/v2/engines/**
        - id: repairs-service
          uri: lb://repairs-service
          predicates:
            - Path=/api/v2/repairs/**