server:
    port: 7080
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/MacarenaSoto/TingesoEntrega2SI
                    search-paths: config-data
    application:
        name: config-service

    